import type { Currency } from '@/lib/types';

export const currencies: Currency[] = [
<<<<<<< HEAD
  { symbol: 'USD', name: 'US Dollar',           flag: '🇺🇸', flagUrl: 'https://flagcdn.com/us.svg' },
  { symbol: 'EUR', name: 'Euro',                flag: '🇪🇺', flagUrl: 'https://flagcdn.com/eu.svg' },
  { symbol: 'GBP', name: 'British Pound',       flag: '🇬🇧', flagUrl: 'https://flagcdn.com/gb.svg' },
  { symbol: 'ZAR', name: 'South African Rand',  flag: '🇿🇦', flagUrl: 'https://flagcdn.com/za.svg' },
  { symbol: 'AUD', name: 'Australian Dollar',   flag: '🇦🇺', flagUrl: 'https://flagcdn.com/au.svg' },
  { symbol: 'CAD', name: 'Canadian Dollar',     flag: '🇨🇦', flagUrl: 'https://flagcdn.com/ca.svg' },
  { symbol: 'JPY', name: 'Japanese Yen',        flag: '🇯🇵', flagUrl: 'https://flagcdn.com/jp.svg' },
  { symbol: 'CHF', name: 'Swiss Franc',         flag: '🇨🇭', flagUrl: 'https://flagcdn.com/ch.svg' },
  { symbol: 'CNY', name: 'Chinese Yuan',        flag: '🇨🇳', flagUrl: 'https://flagcdn.com/cn.svg' },
  { symbol: 'INR', name: 'Indian Rupee',        flag: '🇮🇳', flagUrl: 'https://flagcdn.com/in.svg' },
  { symbol: 'NGN', name: 'Nigerian Naira',      flag: '🇳🇬', flagUrl: 'https://flagcdn.com/ng.svg' },
  { symbol: 'BRL', name: 'Brazilian Real',      flag: '🇧🇷', flagUrl: 'https://flagcdn.com/br.svg' },
  { symbol: 'MXN', name: 'Mexican Peso',        flag: '🇲🇽', flagUrl: 'https://flagcdn.com/mx.svg' },
  { symbol: 'SGD', name: 'Singapore Dollar',    flag: '🇸🇬', flagUrl: 'https://flagcdn.com/sg.svg' },
  { symbol: 'HKD', name: 'Hong Kong Dollar',    flag: '🇭🇰', flagUrl: 'https://flagcdn.com/hk.svg' },
  { symbol: 'NZD', name: 'New Zealand Dollar',  flag: '🇳🇿', flagUrl: 'https://flagcdn.com/nz.svg' },
  { symbol: 'SEK', name: 'Swedish Krona',       flag: '🇸🇪', flagUrl: 'https://flagcdn.com/se.svg' },
  { symbol: 'NOK', name: 'Norwegian Krone',     flag: '🇳🇴', flagUrl: 'https://flagcdn.com/no.svg' },
  { symbol: 'DKK', name: 'Danish Krone',        flag: '🇩🇰', flagUrl: 'https://flagcdn.com/dk.svg' },
  { symbol: 'PLN', name: 'Polish Złoty',        flag: '🇵🇱', flagUrl: 'https://flagcdn.com/pl.svg' },
=======
  { symbol: 'USD', name: 'US Dollar',           flag: '🇺🇸' },
  { symbol: 'EUR', name: 'Euro',                flag: '🇪🇺' },
  { symbol: 'GBP', name: 'British Pound',       flag: '🇬🇧' },
  { symbol: 'ZAR', name: 'South African Rand',  flag: '🇿🇦' },
  { symbol: 'AUD', name: 'Australian Dollar',   flag: '🇦🇺' },
  { symbol: 'CAD', name: 'Canadian Dollar',     flag: '🇨🇦' },
  { symbol: 'JPY', name: 'Japanese Yen',        flag: '🇯🇵' },
  { symbol: 'CHF', name: 'Swiss Franc',         flag: '🇨🇭' },
  { symbol: 'CNY', name: 'Chinese Yuan',        flag: '🇨🇳' },
  { symbol: 'INR', name: 'Indian Rupee',        flag: '🇮🇳' },
  { symbol: 'NGN', name: 'Nigerian Naira',      flag: '🇳🇬' },
  { symbol: 'BRL', name: 'Brazilian Real',      flag: '🇧🇷' },
  { symbol: 'MXN', name: 'Mexican Peso',        flag: '🇲🇽' },
  { symbol: 'SGD', name: 'Singapore Dollar',    flag: '🇸🇬' },
  { symbol: 'HKD', name: 'Hong Kong Dollar',    flag: '🇭🇰' },
  { symbol: 'NZD', name: 'New Zealand Dollar',  flag: '🇳🇿' },
  { symbol: 'SEK', name: 'Swedish Krona',       flag: '🇸🇪' },
  { symbol: 'NOK', name: 'Norwegian Krone',     flag: '🇳🇴' },
  { symbol: 'DKK', name: 'Danish Krone',        flag: '🇩🇰' },
  { symbol: 'PLN', name: 'Polish Złoty',        flag: '🇵🇱' },
>>>>>>> refs/remotes/origin/main
];
